web:
  image: flask
  container_name: flask-web
  ports:
    - "3333:5000"
  volumes:
    - "/home/app/test-task:/webapp"
  external_links:
    - "redis:redis"
  command: gunicorn -w 4 -b 0.0.0.0:5000 main:app

celery:
  image: celery
  container_name: celery-tasks
  environment:
   - C_FORCE_ROOT=true
  volumes:
    - "/home/app/test-task:/celeryapp"
  external_links:
    - "redis:redis"
  command: celery worker -c 10 -A main.celery --loglevel=debug
