web:
  image: flask
  container_name: flask-web
  ports:
    - "3333:5000"
  volumes:
    - "/home/app/test-task:/webapp"
  external_links:
    - "redis:redis"

celery:
  image: celery
  container_name: celery-tasks
  volumes:
    - "/home/app/test-task:/celeryapp"
  external_links:
    - "redis:redis"